### ISSUE TITLE
'Post' does not work from DCOS Scale Strike API

### ISSUE THREAD

**Issue by antman1p** [ngageoint/scale#592] opened 2016-11-08 15:24 UTC
When using the SCale Strike API via DCOS, a 404 error is given.  We had to use the web browser developer tools to change the post action to: /service/scale/api/v4/strikes in order for the post button to work.

**Comment by dfaller** [comment] 2016-11-09 19:12
This issue is a duplicate of #569.

**Closed by dfaller** 2016-11-09 19:12 UTC
