### ISSUE TITLE
Add Node and Exit Code fields to Jobs list

### ISSUE THREAD

**Issue by dickmancj-mil** [ngageoint/scale#429] opened 2016-08-17 20:10 UTC
Requested fields are:
1. Node of last execution
2. Exit code of last execution

These fields are not currently in the REST API response

**Comment by wardcr** [comment] 2016-08-17 20:16
This is somewhat a duplicate of #213 and #325

**Comment by dfaller** [comment] 2017-12-14 15:17
This is OBE.

**Closed by dfaller** 2017-12-14 15:17 UTC
Labels: jobs and recipes, rest api, ui
