### ISSUE TITLE
Support side-car metadata capture from Seed job types

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1228] opened 2018-06-26 21:06 UTC
We need to validate that side-car metadata files are correctly being captured from Seed job types. The format of metadata files is updated to be a purely GeoJSON format. All temporal data will exist in the `properties` member.

**Comment by dfaller** [comment] 2018-07-18 19:19
Duplicate of #1160

**Closed by dfaller** 2018-07-18 19:19 UTC
Labels: jobs and recipes
