### ISSUE TITLE
Sceduler needs updated mesos egg for DCOS deployment

### ISSUE THREAD

**Issue by droessne** [ngageoint/scale#121] opened 2016-03-31 15:03 UTC
The DCOS we have required mesos 0.25.0 so the scheduler will need the following egg to work. 

http://downloads.mesosphere.io/master/centos/7/mesos-0.25.0-py2.7-linux-x86_64.egg

**Comment by tclarke** [comment] 2016-03-31 19:48
Duplicate of #21

**Closed by tclarke** 2016-03-31 19:48 UTC
