### ISSUE TITLE
Filter Overview Page by Operational Jobs

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#539] opened 2016-10-17 21:13 UTC
Add a switch on the overview page to display or hide R&D job types.

This might require a REST API change.

**Comment by dfaller** [comment] 2016-11-04 20:02
Merged into master

**Comment by gisjedi** [comment] 2016-11-11 14:22
This issue is not actually resolved in the desired fashion. It was intended that you could filter the overview page (home page / dashboard) so as to only see the operational jobs state. We don't want the health display going red over jobs that are in R&D states.

**Closed** 2018-08-23 15:33 UTC
Labels: jobs and recipes, rest api, ui
