### ISSUE TITLE
Ingest Scan

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#589] opened 2016-11-07 21:58 UTC
Develop a capability for the ingest process to "scan" a workspace already filled with existing files.

**Comment by wardcr** [comment] 2016-11-14 19:31
This looks like a duplicate of #575

**Comment by dfaller** [comment] 2016-11-14 21:17
Yeah, though the other issue also talks about ingesting via REST API. When it comes time to implement, we'll grab this or the other item.

**Comment by gisjedi** [comment] 2016-12-08 18:17
I'm taking this and beginning the investigation on what all is needed to do a full / filtered workspace scan.

**Closed** 2017-03-02 17:56 UTC
Labels: ingest, storage
