### ISSUE TITLE
AWS S3 eventVersion Update

### ISSUE THREAD

**Issue by afiguly** [ngageoint/scale#1451] opened 2018-11-29 21:37 UTC
It appears that the AWS S3 Service has updated from eventVersion 2.0 to 2.1.  The s3_monitor.py file currently checks for eventVersion == 2.0 for incoming S3/SQS Events, and due to the update, is generating a "mismatch" error.

```
SQSNotificationError: Unable to process message as it does not match EventName and EventVersion:{
  "Records": [
    {
      "eventVersion": "2.1",
      "eventTime": "2018-11-29T15:08:24.087Z",
      "requestParameters": {
        "sourceIPAddress": "1.1.1.1"
      },
 . . . etc., etc.
```

**Comment by JohnPTobe** [comment] 2018-11-30 16:08
Duplicate of #1450

**Closed by JohnPTobe** 2018-11-30 16:08 UTC
