### ISSUE TITLE
Remove Strike NFS Requirement

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#173] opened 2016-04-21 15:47 UTC
I just found that in addition to the ingest job, Strike also is hard coded for NFS only.

**Comment by dfaller** [comment] 2016-04-22 12:46
Yes, this is related to a refactor that will needed in order to have different kinds of Strike processes, such as listening to S3 events.

**Comment by dfaller** [comment] 2016-05-06 14:53
This is really a duplicate of issue #19 so I am closing this.

**Closed by dfaller** 2016-05-06 14:53 UTC
Labels: ingest, storage
